#!/bin/sh

# script/setup: Set up the application for the first time after cloning, or set
#               it back to the initial unused state.

set -e

cd "$(dirname "$0")/.."

echo "==> Dropping and recreating the database..."

dropdb nest-blog-development > /dev/null 2>&1
dropdb nest-blog-test > /dev/null 2>&1

createdb nest-blog-development
createdb nest-blog-test

echo "==> Installing dependencies..."

npm install

echo "==> Running database migrations"

npm run typeorm migration:run

echo "==> Building assets..."

npm run build:assets

